name: eco_alerta_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.2

  sqflite: ^2.0.0+4
  
  path_provider: ^2.0.2

  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  sqflite_common_ffi: 2.3.5

flutter:
  assets: 
    - assets/images/
    - assets/fonts/
  
  # fonts:
  #   - family: Cascadia
  #     fonts:
  #       - asset: assets/

  uses-material-design: true
